### PR TITLE
Add stylesheet link in nwburg template deck.html

### PR DESCRIPTION
**Pull request by matoushs**
In response to issue #105 - add a link to the default wurzburg css file.

### CODE REVIEW

**Comment by matoushs** [comment]
@monofon @mbotsch - I've updated the Wburg CSS to include a link to the default wurzburg css file. Could you please review?  Thank you

**Comment by mbotsch** [comment]
Hi Samantha,
what happens in wburg stays in wburg ;-)
I don't have any slides that I could test with your resource pack. If it looks ok for you then @monofon can probably just merge it.
Best, Mario

**Comment by marcerich** [comment]
> Hi Samantha, what happens in wburg stays in wburg ;-) I don't have any slides that I could test with your resource pack. If it looks ok for you then @monofon can probably just merge it. Best, Mario

Hi all,

of course and I guess its a  misunderstanding (once again ;)...since I think Sam asked for exactly a merge but just was polite not asking for a merge without inspection of *the master* 

Marc

**Comment by monofon** [comment]
My mistake, I forgot to merge this a month ago.

**Pull request merged**
