### PR TITLE
Add Mode Menu

### PR DESCRIPTION
**Pull request by salbeira**
Adds buttons to the main menu that allow you to activate functions previously only available via keyboard shortcuts.

- Presenter Mode
- Recording
- A11y Mode
- Handout Mode

In addition the button that opens the print style of the page was also moved here.

In addition you may now access the slides with `?presenter`, `?a11y` or `?handout` to activate the corresponding mode on startup.

### CODE REVIEW

**Comment by salbeira** [comment]
@mbotsch I did more digging around, trying to find out if there is a way to determine the user's zoomfactor and it seems to be actively and conciously be prohibited by browser manufacturers in order to not allow application developers screw around with it (in order to fight attempts of assistive functions of the browser, like scaling things back down when the user zooms in).

As a reminder where we need that: Entering Handout Mode, on the browsers unmodified zoom level, you determine the ratio between the viewport and reveal's slide width to have the Handout Mode's slides fill the screen. This slideScale factor was before determined dynamically and adjusted on zooming in and out, resulting in the page ignoring the native zoom factor of the user, not allowing one to zoom in or out on desktop (pinch-zoom on mobile was either disabled via meta tags or worked fine if the browser just ignored it). The slideScale value should be a constant determined between the user's browser window's width and reveal's internal width. This would however require that once the user zooms in that we have some way to determine this original window width. No API inside browsers however report this value. Once the user zooms in with CTRL + +/- all values, viewport width, screen width, window inner and outer width as well as the new visualViewport API report the scaled up/down values for width and height. The original, unzoomed values are unavailable and the visualViewport API always reports a scale of "1" as it only considers pinch-zoom scales.

We also should not calculate the value of this slideScale factor on page load because users might enter the page already zoomed in. This would force our handout slides into full screen every time, regardless of what zoom factor the user entered the page with.

There is a way to determine the relation between reveal's slideWidth and the user's window width by factoring in the devicePixelRatio, which gets scaled up and down according to the tab's zoom level. This devicePixelRatio though is reported to be always 2 on Apple devices with Safari because they love their Retina displays so much. At least that is what everyone who asked the same question reports it to be. This is what you can to confirm. The value of devicePixelRatio also does not scale up or down when the user uses CTRL + +/- to change the browser's zoom factor on these device/browser combos.

Some related issues or discussions on this issue:

- https://bugs.webkit.org/show_bug.cgi?id=124862
- https://css-tricks.com/can-javascript-detect-the-browsers-zoom-level/
- https://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers

What I did in the most recent commit is simply remove the fullscreen grow in Handout Mode. If a user wants to have it full screen, they need to adjust their scale manually.

We could add a "fit to screen" button to the zoom buttons that refreshes the slideScale on demand and thus allows users who zoomed in by default to have their choice of what is defined as "full screen scale", but I still do not recommend determining the slideScale once on load as these user's basically have to readjust their browser scale every time they re-enter the page.

**Review by monofon — CHANGES_REQUESTED** [review]
Very nice. Works for me, but seems to only be active for resource-pack *tudo*. Make it available to everyone. Then we can merge this.

**Comment by salbeira** [comment]
What is missing on other resource packs? The changes modify the menu plugin and associated plugins (explain, handout and a11y) that require keyboard shortcuts. If these plugins are in your deck plugins the changes should be reflected accordingly. I just checked for wburg, mono and default and the buttons are available. wburg does not use the a11y plugin and I would rather not touch their templates and defaults.

mono:
grafik

wburg:
grafik

default:
grafik

**Comment by mbotsch** [comment]
Maybe check the index page for the non-TU resource packs?

**Comment by salbeira** [comment]
Ah yes. The tudo pack doesn't overwrite the default index.js. The nwburg resource pack also uses default index.js so I only need to touch the index.css file. The mono resource pack uses a custom index.js. I guess through the request I am allowed to touch it.

**Comment by salbeira** [comment]
@monofon: Just talked with @mbotsch about this: Your resource-pack overwrites the index.js but it seems that it is just a very old copy of the index.js in the default pack. If I insert and adjust the functions needed for the new direct links for your pack it also just turns into the default index.js file. Can I just remove it from your resource-pack?

Additionally: Your hover effect on links is breaking the custom handout mode icon. I can fiddle around in your css files to make it look as it should but I want to be very careful to just touch other member's css files. Should I just prepare the .js stuff and leave the adjustments to you or do you want me to have a "somehow working" css and you do adjustments from there?

**Comment by monofon** [comment]
Now I understand why index.{css,js} needed to be changed. Quite nice.

**Pull request merged**
