### PR TITLE
Don't rsync --delete in Haskell, instead rely on configuration files

### PR DESCRIPTION
**Pull request by kno10**
The --delete option should be chosen by the user via decker.yaml.

### CODE REVIEW

**Comment by monofon** [comment]
Options removed here should be added to `publish.rsync.options` in the `default.yaml` files for all resource packs as to not change the behaviour of existing presentations. We did that for a few options some time ago. I cannot remember why we left these three behind. @mbotsch, @salbeira can you?

**Comment by kno10** [comment]
Relates to #40

**Comment by mbotsch** [comment]
IMO the `--delete` should be enabled by default. Otherwise you might end up with last year's annotations for new lectures. But it should be possible to disable this. I suggest that we move all the default options into `default.yaml`.

**Comment by monofon** [comment]
Fixed in ff171c3e7e9c7a1a963c0d2ef53556809d7c1e86.

**Pull request closed without merging**
